/*
*********************************************************************************************************
*                                                uC/OS-II
*                                          The Real-Time Kernel
*
*                        (c) Copyright 1992-1998, Jean J. Labrosse, Plantation, FL
*                                           All Rights Reserved
*
*                                           MASTER INCLUDE FILE
*********************************************************************************************************
*/

/*
*********************************************************************************************************
* Keil C port.
*********************************************************************************************************
*/

#ifndef __INCLUDES__
#define __INCLUDES__

//os
#include    "uCosii\os_cpu.h"
#include    "uCosii\os_cfg.h"
#include    "uCosii\ucos_ii.h"

//CPU
//#include    "stc15f2k60s2.h"
#include    "user\IAP15W4K61S4.h"

#include 	"stdio.h"
#include 	"intrins.h"
#include 	"string.h"
#include  "source\common.h"
#include  "source\gameCore.h"
#include  "source\tankGame.h"

#endif
